### ISSUE TITLE
Error with running demo on Cheng2020 model

### ISSUE THREAD

**Issue by ZhangYuef** [Eric-qi/RDO-PTQ#1]
The script is:
```bash
python main2.py --arch Cheng2020 --quality 6 --lmbda 0.0483 --save --n_bits_w 8 --channel_wise --type mse --task_loss 2 --init max  --config ./config.yaml
```

Error information:
> 2024-03-27 15:22:13,706 [INFO ]  Logging file is ./results/Cheng2020/mse/6/logs/20240327_152213.log
2024-03-27 15:22:13,706 [INFO ]  [PID] 9421
2024-03-27 15:22:13,706 [INFO ]  ======================= Hyper Parameters =======================
2024-03-27 15:22:13,706 [INFO ]  task loss: 2.0
2024-03-27 15:22:13,706 [INFO ]  calib data: clic41
2024-03-27 15:22:13,706 [INFO ]  param init: max
2024-03-27 15:22:13,706 [INFO ]  channel wise: True
2024-03-27 15:22:13,706 [INFO ]  seed: 1005
2024-03-27 15:22:13,706 [INFO ]  lambda: 0.0483
2024-03-27 15:22:13,706 [INFO ]  iterations: 20000
2024-03-27 15:22:13,707 [INFO ]  batch_size: 4
2024-03-27 15:22:13,707 [INFO ]  loss weight: 0.01
2024-03-27 15:22:13,707 [INFO ]  input drop rate: 0.5
2024-03-27 15:22:13,707 [INFO ]  ========================== Cheng2020 ==========================
2024-03-27 15:22:14,962 [INFO ]  =======================Full-precision model========================
Traceback (most recent call last):
  File "main2.py", line 322, in <module>
    main(sys.argv[1:])
  File "main2.py", line 318, in main
    optimize_model(args, config, output_dir, log_dir)
  File "main2.py", line 171, in optimize_model
    Test_kodak(model)
  File "/RDO-PTQ-main/task-oriented-PTQ/test_datasets.py", line 95, in Test_kodak
    out = model.forward(x_pad)
  File "python3.8/site-packages/compressai/models/google.py", line 537, in forward
    z_hat, z_likelihoods = self.entropy_bottleneck(z)
  File "python3.8/site-packages/torch/nn/modules/module.py", line 1498, in _call_impl
    if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
  File "python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'EntropyBottleneck' object has no attribute '_backward_pre_hooks'

The version for `CompressAI` is `1.2.4`.

**Comment by ZhangYuef** [comment]
It seems to be the confliction between the `EntropyBottleneck`'s implementation in`compressai` and `torch==2.2.1+cu121`.

Error happens with `torch==2.2.1+cu121` and `torchvision==0.17.1+cu121`.
Error disappears with `torch==1.11.0` and `torchvision==0.12.0`.
